version: '3.8'

services:
  app:
    image: patientor.backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:4000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_started
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo_data_prod:/data/db
